@startuml AdminServiceClass
skinparam classAttributeIconSize 0
skinparam backgroundColor #FFFFFF
skinparam roundcorner 8
skinparam shadowlighting false

class AdminService {
    - adminRepo : AdminRepository
    --
    + authenticate(String, String) : boolean
}

@enduml