@startuml MapsServicesClass
skinparam classAttributeIconSize 0
skinparam roundcorner 8
skinparam shadowlighting false


class MapsService {
    + getLatLngFromAddress(String) : LatLng
}

class DistanceMatrixService {
    + buildDistanceMatrix(List<Order>, LatLng) : double[][]
}
@enduml