@startuml OrderServiceClass
skinparam classAttributeIconSize 0
skinparam roundcorner 8
skinparam shadowlighting false

class OrderService {
    + saveOrder(Order) : void
    + getOrdersByUserId(String) : List<Order>
    + getAllOrders() : List<Order>
}
@enduml