######################## SETUP application.properties ########################

## General setup
server.port = 8080
vaadin.launch-browser = true

## Terminal setup - text color, formating, disable logging... 
spring.output.ansi.enabled = always  
logging.pattern.console = %cyan(%d{HH:mm:ss}) [%green(%level)]  %cyan(%msg%n)
logging.level.root = ERROR

## Files Uploading setup
spring.servlet.multipart.enabled = true
spring.servlet.multipart.max-file-size = 16MB
spring.servlet.multipart.max-request-size = 16MB 

## MongoDB setup connection
spring.data.mongodb.uri = mongodb+srv://yahavr:12345@cluster0.zmbepyg.mongodb.net/demoDB

##google maps API
google.maps.api.key = AIzaSyCbO34-e6pyTVH-M1uQPGmsLko23dpXzB8
#############################################################################