@startuml
skinparam classAttributeIconSize 0
skinparam ranksep 1
skinparam nodesep 30
hide members

package "UI" {
 class AdminManagementView
 class AlgorithmRunnerView
 class CreateOrderView
 class LoginView
 class RegisterView
 class SavedRoutsView
 class UserDetailsView
 class GoogleMapView

    ' אילוץ מבנה אנכי מדויק בתוך החבילה
    AdminManagementView -[hidden]down- AlgorithmRunnerView
    AlgorithmRunnerView -[hidden]down- CreateOrderView
    CreateOrderView -[hidden]down- LoginView
    LoginView -[hidden]down- RegisterView
    RegisterView -[hidden]down- SavedRoutsView
    SavedRoutsView -[hidden]down- UserDetailsView
    UserDetailsView -[hidden]down- GoogleMapView
}

package "Service" {
 class WarehouseService
 class VehicleService
 class OrderService
 class GeneticRoutingService
 class MapsService
 class DistanceMatrixService
 class RouteService
 class AdminService
 class UserService

    ' אילוץ מבנה אנכי מדויק בתוך החבילה
    WarehouseService -[hidden]down- VehicleService
    VehicleService -[hidden]down- OrderService
    OrderService -[hidden]down- GeneticRoutingService
    GeneticRoutingService -[hidden]down- MapsService
    MapsService -[hidden]down- DistanceMatrixService
    DistanceMatrixService -[hidden]down- RouteService
    RouteService -[hidden]down- AdminService
    AdminService -[hidden]down- UserService
}

' הגדרת קשרי תלות (Dependency) מקצה לקצה עם כיוון ברור ימינה
AdminManagementView -up-* WarehouseService
AdminManagementView -up-* VehicleService
AdminManagementView -up-* MapsService

AlgorithmRunnerView -up-* OrderService
AlgorithmRunnerView -up-* VehicleService
AlgorithmRunnerView -up-* WarehouseService
AlgorithmRunnerView -up-* GeneticRoutingService
AlgorithmRunnerView -up-* DistanceMatrixService
AlgorithmRunnerView -up-* RouteService

CreateOrderView -up-* MapsService
CreateOrderView -up-* OrderService
' קשר בתוך חבילת ה-UI ולכן לא מכריחים אותו ימינה
CreateOrderView --* GoogleMapView 

LoginView -up-* AdminService
LoginView -up-* UserService

RegisterView -up-* UserService

SavedRoutsView -up-* RouteService
SavedRoutsView -up-* VehicleService
SavedRoutsView -up-* OrderService

UserDetailsView -up-* UserService

UI -[hidden]- Service
@enduml