@startuml CreateOrderViewClass
skinparam classAttributeIconSize 0
skinparam backgroundColor #FFFFFF
skinparam roundcorner 8
skinparam shadowlighting false

class CreateOrderView {
    - mapsService : MapsService
    - orderService : OrderService
    - map : GoogleMapComponent
    - currentLat : double
    - currentLng : double
    - isLocationVerified : boolean
    --
    + CreateOrderView(MapsService, OrderService, String)
    - btnCheckAddress_Click() : void
    - btnSave_Click() : void
}
@endif